---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-hotfix
  namespace: hotfix
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:hotfix-*
spec:
  releaseName: podinfo-hotfix
  chart:
    git: git@github.com:seanmcrw/gitops-helm
    path: charts/podinfo
    ref: master
  values:
    image: seanmcguigan/podinfo:dev-rbh8myjb
    replicaCount: 1
    hpa:
      enabled: false