---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-uat
  namespace: uat
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:uat-*
spec:
  releaseName: podinfo-uat
  chart:
    git: git@github.com:seanmcrw/gitops-helm
    path: charts/podinfo
    ref: master
  values:
    image: seanmcguigan/podinfo:bugfix-6aqgkcz8
    replicaCount: 1
    hpa:
      enabled: false
